name: Update WakaTime stats

on:
  schedule:
    - cron: "0 */12 * * *"   # 00:00 & 12:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Jakarta
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: "true"
          # RANGE: last_7_days | last_30_days | last_year | all_time
          RANGE: "last_7_days"
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
          # Batasi/atur bahasa yang mau tampil
          LANG_COUNT: "8"
          IGNORED_LANGUAGES: "Text, Other"
